/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef VDRIFT_PRIVATE_H
#define VDRIFT_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2007.3.23.1"
#define VER_MAJOR	2007
#define VER_MINOR	3
#define VER_RELEASE	23
#define VER_BUILD	1
#define COMPANY_NAME	""
#define FILE_VERSION	"2007-03-23"
#define FILE_DESCRIPTION	"VDrift Win32"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"GNU GPL v2"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"vdrift.exe"
#define PRODUCT_NAME	"VDrift"
#define PRODUCT_VERSION	""

#endif /*VDRIFT_PRIVATE_H*/
