#ifndef _RENDERSTATUSVERBOSITY_H
#define _RENDERSTATUSVERBOSITY_H

enum RendererStatusVerbosity
{
	VERBOSITY_MINIMUM = 0,
	VERBOSITY_PASSBRIEF = 0,
	VERBOSITY_PASSDETAIL,
	VERBOSITY_MODELS,
	VERBOSITY_MODELS_TEXTURES,
	VERBOSITY_MODELS_TEXTURES_UNIFORMS,
	VERBOSITY_MAXIMUM = VERBOSITY_MODELS_TEXTURES_UNIFORMS
};

#endif
