#-------------#
# Import Vars #
#-------------#
Import('*')

src = Split("""anjuta/VDrift.prj
               anjuta/VDrift.pws
               autopackage/vdrift.apspec
               autopackage/vdrift.desktop
               cars/blank.car
               debian/changelog
               debian/compat
               debian/control
               debian/copyright
               debian/vdrift.dirs
               debian/vdrift.install
               debian/vdrift-data.dirs
               debian/vdrift-data.install
               debian/docs
               debian/manpage.xml.ex
               debian/menu.ex
               debian/rules
               debian/watch.ex
               debian/cdbs/scons-vars.mk
               debian/cdbs/scons.mk
               scripts/Makefile
               scripts/configure
               scripts/vdrift-install.sh
               valgrind/vdrift.supp
               win/controls
               win/header.bmp
               win/welcome-installer.bmp
               win/welcome-uninstaller.bmp
               win/VDrift.dev
               win/VDrift.ico
               win/vdrift.nsi
               win/VDrift_private.h
               win/VDrift_private.rc
               win/dll/SDL.dll
               win/dll/SDL_image.dll
               win/dll/SDL_net.dll
               win/dll/jpeg.dll
               win/dll/libpng12.dll
               win/dll/zlib1.dll
               Doxyfile
               scons-local-0.96.95.tar.gz""")

#-----------------------#
# Distribute to src_dir #
#-----------------------#
dist_files = ['SConscript'] + src

env.Distribute (src_dir, dist_files)

#----------------#
# Subdirectories #
#----------------#
Export(['env', 'src_dir', 'bin_dir'])
#SConscript("osx/SConscript")
